### ISSUE TITLE
Track response rate for streaming calls

### ISSUE THREAD

**Issue by steven-sheehy** [bojand/ghz#196]
**Is your feature request related to a problem? Please describe.**
My API uses server streaming to send message to clients and I can't view the response rate without viewing server logs.

**Describe the solution you'd like**
Track and output response rate similarly as requests/second is displayed.

```
Summary:
  Count:	 100
  Total:	 120.01 s
  Slowest:	 110.45 s
  Fastest:	 14.74 s
  Average:	 99.97 s
  Requests/sec:	 0.83
  Responses/sec: 587     <- new
```

A response rate histogram would also be very beneficial.

**Describe alternatives you've considered**

**Additional context**
